### ISSUE TITLE
Feature request: Metric units

### ISSUE THREAD

**Issue by kthelgason** [lexiross/fattest-cat#11]
This is a brilliant idea unfortunately rendered useless for me and those on my side of the Atlantic. We don't understand these made-up units!

Would there be interest in adding a flag that gets you results in metric?

**Comment by lexiross** [comment]
Great idea @kthelgason - if you or anyone else submits a PR for this I will happily merge :)

**Comment by peterkhayes** [comment]
Implemented and merged - see readme
