### ISSUE TITLE
Syntax Error on Node v5.1.0

### ISSUE THREAD

**Issue by matthewpoer** [lexiross/fattest-cat#5]
Immediately upon installation & execution of `fattest-cat`,

~~~
$ fattest-cat 
/usr/local/lib/node_modules/fattest-cat/index.js:7
const {uniq, compact} = require("lodash");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

~~~

**Comment by antony** [comment]
You are using a version of node which is too old.

You will probably need Node v6 or v7.

**Comment by matthewpoer** [comment]
Indeed. Thanks, @antony 

FWIW, I found that if I restructure that line and use strict mode, all is well:
~~~
#!/usr/bin/env node
'use strict';
const request         = require("request-promise");
const opener          = require("opener");
const Promise         = require("bluebird");
const cheerio         = require("cheerio");
// const {uniq, compact} = require("lodash");
const uniq            = require("lodash");
const compact         = require("lodash");
~~~

Would making this change break the script for newer versions of node?

Alternatively, `package.json` could specify the min. required node version in the [engine param](https://docs.npmjs.com/files/package.json#engines)

**Comment by junedomingo** [comment]
#6 This will support node version <= 6

**Comment by matthewpoer** [comment]
@junedomingo, How does this support Node v5? I checked out your `master` branch directly to test and it gave the same error as `lexiross:master` did. 

~~~
$ node --version
v5.1.0

$ git clone https://github.com/junedomingo/fattest-cat.git && cd fattest-cat
Cloning into 'fattest-cat'...
remote: Counting objects: 84, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 84 (delta 42), reused 73 (delta 31), pack-reused 0
Unpacking objects: 100% (84/84), done.
Checking connectivity... done.

$ git log -2
commit 0e29b158601aa4b9e8c73097b1aa7620bcbcdc88
Author: June Domingo <june@cynder.io>
Date:   Thu Mar 2 23:09:40 2017 +0800

    Highlighted the fattest! <U+1F640>

commit 58136b12fbf58570e92d85f8dd332e63b7e44c92
Author: June Domingo <june@cynder.io>
Date:   Thu Mar 2 23:08:11 2017 +0800

    Added support for Node version <= 5

$ node index.js 
/Users/matthewpoer/Desktop/fattest-cat/index.js:7
const {uniq, compact} = require("lodash");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
~~~

Even if you restructure the `const {uniq, compact}` line a bit, you have `let fattestCat = {lbs: 0, oz: 0};`, and if I enable strict mode to work around that, I end up with 

~~~
$ node index.js 
module.js:340
    throw err;
    ^

Error: Cannot find module 'request-promise'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/matthewpoer/Desktop/fattest-cat/index.js:3:25)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
~~~

If the code and its dependencies all need Node 6+, I think that's fine, we just need to specify that in the README or in the package (or both).

**Comment by antony** [comment]
Unless I'm missing something, this is a quick node prototype to find fat cats using screen scraping with cheerio.

Do we really need an endless discussion on supporting legacy node versions (btw, if you are using node < 6, focus on upgrading, not retrofitting).

It's just for fun - could you be better using your time?

**Comment by junedomingo** [comment]
@matthewpoer , from my repo , do the ff:

`npm install`
`npm install -g`

`fattest-cat`

it should work now.
if @lexiross merge it, then you can just install it from npm reg. `npm install fattest-cat -g`

**Comment by matthewpoer** [comment]
@antony I agree, it's just for fun.

I know little to nothing about node and this is just an excuse to play with it. I found a bug when I ran the script, so I reported it. You're not required to participate in the fix or the discussion. No one is. 

To me this is a fun/silly example of basic node concepts, (syntax, web requests, packaging, etc.). I was considering publishing a docker image leveraging it and offering fattest-cat-as-a-service. See? this is fun for me. What a fun example to play with while learning new tools and technologies. 

@junedomingo that got me past the `throw err;` bit, thanks. I still had to add `use strict` and adjust the `const` block though, so I don't think we can say that this supports Node 5.1.0 yet. Want me to push you my changes and you can include them in your PR?

**Comment by junedomingo** [comment]
@matthewpoer , mhmm.. if you go to my repo and run  `npm install -g`, did you see this line?
`> node_modules/babel-cli/bin/babel.js index.js --out-dir lib`

if not, you can do it manually by typing `npm run prepublish`, after that

`node lib/index.js`

**Comment by matthewpoer** [comment]
@junedomingo I ran it again and did see this line. Not sure if it was there the first time or not, but yes, `node lib/index.js` does work. It's `node index.js` that didn't, but I see now that the updated packaging has `fattest-cat` pointing correctly, and that works for me at this point. Good to go, thanks!

**Comment by antony** [comment]
Hi @matthewpoer - absolutely. You are of course right. It's a great way to learn.

In that case though, I would re-iterate that retrofitting to now unsupported node versions is not a very useful thing to learn - the lowest supported version of node is now v6 - anybody using a lower version really needs to upgrade. Definitely running a node project through babel is really inadvisable - it makes debugging / testing / packaging a pain. Great for client-side (web) code though.

So why not base your work on node v6 +, and think about your docker/SaaS solutions - I'd recommend looking at [HapiJS](http://www.hapijs.com) as a web application framework, and [Node/Alpine](https://hub.docker.com/_/node/) tagged docker images, for a really lightweight deployment solution. Not to mention hosting it on DockerCloud or Kubernetes.

**Comment by lexiross** [comment]
Thanks @matthewpoer for reporting this and thanks @junedomingo for the PR!! However, I'm inclined to go with @antony on this one - I'd rather not use babel in this project, and I think it's fine to just support node versions 6+. I added an `engines` line to package.json and updated the README: https://github.com/lexiross/fattest-cat/commit/3327afd7d0cd164ad9c8635f99ead01654b8d12c

@antony I'll look into some of those other tools when I get a chance ;) (I got an email about Clay which looks promising...)
