### ISSUE TITLE
Feature request: I need the fattest dog too

### ISSUE THREAD

**Issue by jamesduffy** [lexiross/fattest-cat#8]
I like to be an inclusive household of lazy animals

**Comment by peterkhayes** [comment]
I think we'd like to avoid feature creep on this project, but if you fork the repo and switch the url from `/adoptions/cats` to `/adoptions/dogs` everything will work just fine.

The current fattest dog is Camry who weighs 63 lbs 14 oz.
https://www.sfspca.org/adoptions/pet-details/34731346

**Comment by jamesduffy** [comment]
I went ahead and did this. https://github.com/jamesduffy/fattest-dog
